import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import { mkdtemp, rm, mkdir, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import {
  runEvolveCommand,
  parseProposalsFromMarkdown,
  buildImplementationPrompt,
  parseChangedFiles,
  upgradeToSdkLane,
  type EvolveCommandOptions,
  type ExecResult,
  type ParsedProposal,
} from '../src/commands/evolve.js';
import type { RalphResult } from '../src/commands/ralph.js';
import type { Sandbox } from '../src/sandbox/index.js';

// ────────────────────────────────────────────────────────────────────
// Pure-helper tests
// ────────────────────────────────────────────────────────────────────

describe('parseProposalsFromMarkdown', () => {
  const SAMPLE = `# Reflection — 2026-04-28

> Generated by \`frqncy-harness reflect\`.

## Run metadata

- **Generated:** 2026-04-28T12:00:00.000Z

---

## Recurring failure modes

### 1. Tone drift on long-form content

- **Frequency:** 3 of 5 traces
- **Pattern:** the model defaults to startup-bro register on prompts longer than 300 tokens
- **Example trace:** \`abc12345-1111-4111-8111-111111111111\`
- **Recommended fix:** \`b\` — new skill \`brand-voice-anchor\` that re-injects FRQNCY's voice on every long-form turn
- **Estimated complexity:** small

### 2. Ungrounded claims

- **Frequency:** 2 of 5 traces
- **Pattern:** confident assertions without sources
- **Example trace:** \`def67890-2222-4222-8222-222222222222\`
- **Recommended fix:** \`a\` — new \`pre-publish-fact-check\` hook
- **Estimated complexity:** medium

### 3. Empty completion-promise checks

- **Frequency:** 2 of 5 traces
- **Pattern:** loops emit DONE even when work is incomplete
- **Recommended fix:** \`d\` — codify trace \`ghi11111-3333-4333-8333-333333333333\`
- **Estimated complexity:** small

## Synthesis

Ship fix #3 first.`;

  it('extracts all proposals with index, name, pattern, recommendedFix, fixCategory', () => {
    const proposals = parseProposalsFromMarkdown(SAMPLE);
    expect(proposals).toHaveLength(3);

    expect(proposals[0]!.index).toBe(1);
    expect(proposals[0]!.name).toBe('Tone drift on long-form content');
    expect(proposals[0]!.pattern).toMatch(/startup-bro/);
    expect(proposals[0]!.fixCategory).toBe('b');
    expect(proposals[0]!.exampleTrace).toMatch(/abc12345/);

    expect(proposals[1]!.fixCategory).toBe('a');
    expect(proposals[2]!.fixCategory).toBe('d');
  });

  it('returns empty when no Recurring failure modes section exists', () => {
    expect(parseProposalsFromMarkdown('# Other doc\n\nNo proposals here.')).toEqual([]);
  });

  it('returns empty when section exists but has no ### N. headings', () => {
    expect(parseProposalsFromMarkdown('## Recurring failure modes\n\nNo proposals.\n\n## Synthesis\n')).toEqual([]);
  });

  it('preserves the rawSection so the implementation prompt can include the full text', () => {
    const proposals = parseProposalsFromMarkdown(SAMPLE);
    expect(proposals[0]!.rawSection).toContain('### 1. Tone drift on long-form content');
    expect(proposals[0]!.rawSection).toContain('Frequency:');
    expect(proposals[0]!.rawSection).toContain('Recommended fix:');
  });

  it('does not bleed the Synthesis section into the last proposal', () => {
    const proposals = parseProposalsFromMarkdown(SAMPLE);
    expect(proposals[2]!.rawSection).not.toContain('Synthesis');
  });

  it('marks fixCategory as unknown when the recommended fix lacks a leading code', () => {
    const md = `## Recurring failure modes

### 1. Mystery

- **Pattern:** unclear
- **Recommended fix:** just do something
- **Estimated complexity:** small`;
    const proposals = parseProposalsFromMarkdown(md);
    expect(proposals[0]!.fixCategory).toBe('unknown');
  });
});

describe('buildImplementationPrompt', () => {
  const proposal: ParsedProposal = {
    index: 1,
    name: 'Tone drift',
    pattern: 'startup-bro',
    recommendedFix: '`b` — new skill `brand-voice-anchor`',
    fixCategory: 'b',
    rawSection: '### 1. Tone drift\n\n- Pattern: startup-bro',
  };

  it('includes the inoculation sentence (load-bearing safety hook)', () => {
    const prompt = buildImplementationPrompt({
      proposal,
      cwd: '/proj',
      reflectionPath: '/proj/proposals/reflection-2026-04-28.md',
      completionPromise: '<promise>EVOLVE COMPLETE</promise>',
    });
    expect(prompt.toLowerCase()).toMatch(/reward.hacking/);
  });

  it('includes the proposal raw section, working dir, and completion predicate', () => {
    const prompt = buildImplementationPrompt({
      proposal,
      cwd: '/proj',
      reflectionPath: '/proj/proposals/r.md',
      completionPromise: '<promise>EVOLVE COMPLETE</promise>',
    });
    expect(prompt).toContain('### 1. Tone drift');
    expect(prompt).toContain('/proj');
    expect(prompt).toContain('<promise>EVOLVE COMPLETE</promise>');
  });

  it('forbids modifying anchor files (rubrics, AGENT.md locked decisions, the proposal doc itself)', () => {
    const prompt = buildImplementationPrompt({
      proposal,
      cwd: '/proj',
      reflectionPath: '/proj/proposals/r.md',
      completionPromise: 'X',
    });
    expect(prompt).toContain('rubrics/');
    expect(prompt).toContain('SELF-IMPROVING-HARNESS.md');
    expect(prompt.toLowerCase()).toMatch(/do not.*modify/);
  });

  it('explicitly forbids opening a PR or merging', () => {
    const prompt = buildImplementationPrompt({
      proposal,
      cwd: '/proj',
      reflectionPath: '/proj/proposals/r.md',
      completionPromise: 'X',
    });
    expect(prompt.toLowerCase()).toMatch(/do not.*push|do not.*merge|do not.*open a pr/);
  });

  it('explicitly forbids fabricating completion to escape a hard problem', () => {
    const prompt = buildImplementationPrompt({
      proposal,
      cwd: '/proj',
      reflectionPath: '/proj/proposals/r.md',
      completionPromise: 'X',
    });
    expect(prompt.toLowerCase()).toMatch(/do not.*emit.*to escape|escape a hard problem/);
  });
});

describe('parseChangedFiles', () => {
  it('parses a git diff --name-only output', () => {
    expect(parseChangedFiles('src/foo.ts\nsrc/bar.ts\n\n')).toEqual(['src/foo.ts', 'src/bar.ts']);
  });

  it('returns empty for empty input', () => {
    expect(parseChangedFiles('')).toEqual([]);
    expect(parseChangedFiles('\n\n')).toEqual([]);
  });

  it('trims whitespace per line', () => {
    expect(parseChangedFiles('  src/foo.ts  \nsrc/bar.ts')).toEqual(['src/foo.ts', 'src/bar.ts']);
  });
});

describe('upgradeToSdkLane', () => {
  it('promotes anthropic/* to claude-sdk/* (so tools work in-process)', () => {
    expect(upgradeToSdkLane('anthropic/claude-sonnet-4-6')).toBe('claude-sdk/claude-sonnet-4-6');
    expect(upgradeToSdkLane('anthropic/claude-opus-4-6')).toBe('claude-sdk/claude-opus-4-6');
  });

  it('passes other lanes through unchanged', () => {
    expect(upgradeToSdkLane('claude-sdk/claude-sonnet-4-6')).toBe('claude-sdk/claude-sonnet-4-6');
    expect(upgradeToSdkLane('claude-code/sonnet')).toBe('claude-code/sonnet');
    expect(upgradeToSdkLane('openai/gpt-5')).toBe('openai/gpt-5');
    expect(upgradeToSdkLane('openrouter/x/y')).toBe('openrouter/x/y');
  });
});

// ────────────────────────────────────────────────────────────────────
// Integration tests (ralphFn + execFn seams)
// ────────────────────────────────────────────────────────────────────

describe('runEvolveCommand', () => {
  let cwd: string;
  let stdoutBuffer: string;
  let stderrBuffer: string;
  let originalStdout: typeof process.stdout.write;
  let originalStderr: typeof process.stderr.write;

  beforeEach(async () => {
    cwd = await mkdtemp(join(tmpdir(), 'evolve-test-'));
    stdoutBuffer = '';
    stderrBuffer = '';
    originalStdout = process.stdout.write.bind(process.stdout);
    originalStderr = process.stderr.write.bind(process.stderr);
    process.stdout.write = ((chunk: string | Uint8Array): boolean => {
      stdoutBuffer += typeof chunk === 'string' ? chunk : chunk.toString();
      return true;
    }) as typeof process.stdout.write;
    process.stderr.write = ((chunk: string | Uint8Array): boolean => {
      stderrBuffer += typeof chunk === 'string' ? chunk : chunk.toString();
      return true;
    }) as typeof process.stderr.write;
  });

  afterEach(async () => {
    process.stdout.write = originalStdout;
    process.stderr.write = originalStderr;
    await rm(cwd, { recursive: true, force: true });
  });

  // Helpers ────────────────────────────────────────────────

  async function seedReflection(filename: string, body: string): Promise<string> {
    const dir = join(cwd, 'proposals');
    await mkdir(dir, { recursive: true });
    const path = join(dir, filename);
    await writeFile(path, body, 'utf-8');
    return path;
  }

  const REFLECTION_BODY = `# Reflection — 2026-04-28

## Recurring failure modes

### 1. The thing

- **Frequency:** 3 of 5 traces
- **Pattern:** something specific
- **Example trace:** \`abc12345-1111-4111-8111-111111111111\`
- **Recommended fix:** \`b\` — new skill \`brand-anchor\`
- **Estimated complexity:** small

### 2. Other thing

- **Pattern:** another specific thing
- **Recommended fix:** \`a\` — new hook
- **Estimated complexity:** medium

## Synthesis

Ship #1 first.`;

  function makeRalphStub(status: RalphResult['status']): NonNullable<EvolveCommandOptions['ralphFn']> {
    return async (_prompt: string, options: { until?: string; threadId?: string; maxIterations?: number }) => ({
      status,
      iterations: [
        {
          iteration: 1,
          conversationId: 'aa-bb',
          costUsd: 0.01,
          finalText: status === 'completed' ? `done ${options.until ?? ''}` : 'still working',
          predicateMatched: status === 'completed',
        },
      ],
      threadId: options.threadId ?? 'evolve-stub',
      totalCostUsd: 0.01,
      finalText: status === 'completed' ? `done ${options.until ?? ''}` : 'still working',
      completed: status === 'completed',
    });
  }

  function makeExecStub(handlers: Record<string, ExecResult>): NonNullable<EvolveCommandOptions['execFn']> {
    return async (cmd, args) => {
      const key = `${cmd} ${args.join(' ')}`;
      // exact match first, then prefix match
      if (handlers[key]) return handlers[key]!;
      for (const [k, v] of Object.entries(handlers)) {
        if (key.startsWith(k)) return v;
      }
      return { stdout: '', stderr: '', exitCode: 0 };
    };
  }

  // Tests ──────────────────────────────────────────────────

  it('happy path: completed ralph + passing tests = status completed', async () => {
    await seedReflection('reflection-2026-04-28.md', REFLECTION_BODY);
    const result = await runEvolveCommand({
      cwd,
      yes: true, // bypass dirty-tree check
      ralphFn: makeRalphStub('completed'),
      execFn: makeExecStub({
        'npm test': { stdout: 'ok', stderr: '', exitCode: 0 },
        'git diff': { stdout: 'src/skills/brand-anchor.ts\n', stderr: '', exitCode: 0 },
      }),
    });
    expect(result.status).toBe('completed');
    expect(result.proposal?.index).toBe(1);
    expect(result.proposal?.name).toBe('The thing');
    expect(result.testResult?.passed).toBe(true);
    expect(result.changedFiles).toContain('src/skills/brand-anchor.ts');
  });

  it('honors --proposal N to pick a non-default', async () => {
    await seedReflection('reflection-2026-04-28.md', REFLECTION_BODY);
    const result = await runEvolveCommand({
      cwd,
      yes: true,
      proposal: 2,
      ralphFn: makeRalphStub('completed'),
      execFn: makeExecStub({ 'npm test': { stdout: 'ok', stderr: '', exitCode: 0 } }),
    });
    expect(result.proposal?.index).toBe(2);
    expect(result.proposal?.name).toBe('Other thing');
    expect(result.proposal?.fixCategory).toBe('a');
  });

  it('refuses --proposal that is out of range', async () => {
    await seedReflection('reflection-2026-04-28.md', REFLECTION_BODY);
    await expect(
      runEvolveCommand({
        cwd,
        yes: true,
        proposal: 99,
        ralphFn: makeRalphStub('completed'),
        execFn: makeExecStub({}),
      }),
    ).rejects.toThrow(/out of range/);
  });

  it('returns no_reflection when no reflection file exists', async () => {
    const result = await runEvolveCommand({
      cwd,
      yes: true,
      ralphFn: makeRalphStub('completed'),
      execFn: makeExecStub({}),
    });
    expect(result.status).toBe('no_reflection');
    expect(result.proposal).toBeNull();
  });

  it('honors an explicit --reflection path', async () => {
    const path = await seedReflection('custom-name.md', REFLECTION_BODY);
    const result = await runEvolveCommand({
      cwd,
      yes: true,
      reflectionPath: 'proposals/custom-name.md',
      ralphFn: makeRalphStub('completed'),
      execFn: makeExecStub({ 'npm test': { stdout: 'ok', stderr: '', exitCode: 0 } }),
    });
    expect(result.reflectionPath).toBe(path);
  });

  it('refuses on a dirty working tree without --yes', async () => {
    await seedReflection('reflection-2026-04-28.md', REFLECTION_BODY);
    const result = await runEvolveCommand({
      cwd,
      ralphFn: makeRalphStub('completed'),
      execFn: makeExecStub({
        'git status': { stdout: ' M src/foo.ts\n', stderr: '', exitCode: 0 },
      }),
    });
    expect(result.status).toBe('dirty_tree');
    expect(stderrBuffer).toMatch(/uncommitted changes/);
  });

  it('proceeds on a dirty working tree when --yes is passed', async () => {
    await seedReflection('reflection-2026-04-28.md', REFLECTION_BODY);
    const result = await runEvolveCommand({
      cwd,
      yes: true,
      ralphFn: makeRalphStub('completed'),
      execFn: makeExecStub({
        'git status': { stdout: ' M src/foo.ts\n', stderr: '', exitCode: 0 },
        'npm test': { stdout: 'ok', stderr: '', exitCode: 0 },
      }),
    });
    expect(result.status).toBe('completed');
  });

  it('returns ralph_failed when the inner ralph loop does not complete', async () => {
    await seedReflection('reflection-2026-04-28.md', REFLECTION_BODY);
    const result = await runEvolveCommand({
      cwd,
      yes: true,
      ralphFn: makeRalphStub('exhausted'),
      execFn: makeExecStub({}),
    });
    expect(result.status).toBe('ralph_failed');
    expect(result.testResult).toBeUndefined();
  });

  it('returns tests_failed when ralph completes but npm test exits non-zero', async () => {
    await seedReflection('reflection-2026-04-28.md', REFLECTION_BODY);
    const result = await runEvolveCommand({
      cwd,
      yes: true,
      ralphFn: makeRalphStub('completed'),
      execFn: makeExecStub({
        'npm test': { stdout: 'failed', stderr: '5 tests failed', exitCode: 1 },
      }),
    });
    expect(result.status).toBe('tests_failed');
    expect(result.testResult?.passed).toBe(false);
    expect(stderrBuffer).toMatch(/tests failed/);
  });

  it('skips test verification when --skip-verify is set', async () => {
    await seedReflection('reflection-2026-04-28.md', REFLECTION_BODY);
    const result = await runEvolveCommand({
      cwd,
      yes: true,
      skipVerify: true,
      ralphFn: makeRalphStub('completed'),
      execFn: makeExecStub({}),
    });
    expect(result.status).toBe('completed');
    expect(result.testResult).toBeUndefined();
  });

  it('emits structured JSON on --json', async () => {
    await seedReflection('reflection-2026-04-28.md', REFLECTION_BODY);
    const result = await runEvolveCommand({
      cwd,
      yes: true,
      json: true,
      ralphFn: makeRalphStub('completed'),
      execFn: makeExecStub({ 'npm test': { stdout: 'ok', stderr: '', exitCode: 0 } }),
    });
    const parsed = JSON.parse(stdoutBuffer.split('\n').filter(Boolean).join('\n'));
    expect(parsed.status).toBe('completed');
    expect(parsed.proposal.name).toBe('The thing');
    expect(parsed.threadId).toBe(result.threadId);
  });

  it('passes the upgraded SDK lane to ralph when an anthropic API model is given', async () => {
    await seedReflection('reflection-2026-04-28.md', REFLECTION_BODY);
    let observedModel = '';
    const ralphFn: NonNullable<EvolveCommandOptions['ralphFn']> = async (_prompt, options) => {
      observedModel = options.model ?? '';
      return makeRalphStub('completed')(_prompt, options);
    };
    await runEvolveCommand({
      cwd,
      yes: true,
      model: 'anthropic/claude-sonnet-4-6',
      ralphFn,
      execFn: makeExecStub({ 'npm test': { stdout: 'ok', stderr: '', exitCode: 0 } }),
    });
    expect(observedModel).toBe('claude-sdk/claude-sonnet-4-6');
  });

  it('returns gate_blocked when the agent modifies an anchored file', async () => {
    await seedReflection('reflection-2026-04-28.md', REFLECTION_BODY);
    const result = await runEvolveCommand({
      cwd,
      yes: true,
      ralphFn: makeRalphStub('completed'),
      execFn: makeExecStub({
        // git diff --name-only HEAD includes a rubric file the agent shouldn't touch
        'git diff --name-only HEAD': { stdout: 'rubrics/brand-voice.md\n', stderr: '', exitCode: 0 },
        // Per-path diff (called for each changed file)
        'git diff --no-color HEAD --': { stdout: '+some change\n', stderr: '', exitCode: 0 },
        'npm test': { stdout: 'should-not-run', stderr: '', exitCode: 0 },
      }),
    });
    expect(result.status).toBe('gate_blocked');
    expect(result.gateResult?.passed).toBe(false);
    expect(result.gateResult?.details?.failingGate).toBe('rubric-anchor');
    // npm test must NOT have been reached
    expect(result.testResult).toBeUndefined();
  });

  it('returns gate_blocked when the agent introduces a banned voice phrase', async () => {
    await seedReflection('reflection-2026-04-28.md', REFLECTION_BODY);
    const result = await runEvolveCommand({
      cwd,
      yes: true,
      ralphFn: makeRalphStub('completed'),
      execFn: makeExecStub({
        'git diff --name-only HEAD': { stdout: 'src/copy.md\n', stderr: '', exitCode: 0 },
        'git diff --no-color HEAD --': {
          stdout: '+unlock the value of synergy\n',
          stderr: '',
          exitCode: 0,
        },
        'npm test': { stdout: 'should-not-run', stderr: '', exitCode: 0 },
      }),
      loadVoiceAnchorFn: async () => ({
        bannedPhrases: ['unlock', 'synergy'],
        bannedInCodeComments: [],
      }),
    });
    expect(result.status).toBe('gate_blocked');
    expect(result.gateResult?.details?.failingGate).toBe('voice-anchor');
    expect(result.testResult).toBeUndefined();
  });

  it('skips the pre-evolve gate when --skip-gate is set (NOT recommended)', async () => {
    await seedReflection('reflection-2026-04-28.md', REFLECTION_BODY);
    const result = await runEvolveCommand({
      cwd,
      yes: true,
      skipGate: true,
      ralphFn: makeRalphStub('completed'),
      execFn: makeExecStub({
        'git diff --name-only HEAD': { stdout: 'rubrics/brand.md\n', stderr: '', exitCode: 0 },
        'git diff --no-color HEAD --': { stdout: '+anything\n', stderr: '', exitCode: 0 },
        'npm test': { stdout: 'ok', stderr: '', exitCode: 0 },
      }),
    });
    // With --skip-gate, the rubric violation does NOT block; tests run; status is completed
    expect(result.status).toBe('completed');
    expect(result.gateResult).toBeUndefined();
    expect(result.testResult?.passed).toBe(true);
  });

  it('runs gate then npm test on a clean change set', async () => {
    await seedReflection('reflection-2026-04-28.md', REFLECTION_BODY);
    const result = await runEvolveCommand({
      cwd,
      yes: true,
      ralphFn: makeRalphStub('completed'),
      execFn: makeExecStub({
        'git diff --name-only HEAD': { stdout: 'src/skills/brand-anchor.ts\n', stderr: '', exitCode: 0 },
        'git diff --no-color HEAD --': {
          stdout: '+const x = "clean addition";\n',
          stderr: '',
          exitCode: 0,
        },
        'npm test': { stdout: 'ok', stderr: '', exitCode: 0 },
      }),
    });
    expect(result.status).toBe('completed');
    expect(result.gateResult?.passed).toBe(true);
    expect(result.testResult?.passed).toBe(true);
  });

  it('returns pr_opened when --auto-pr succeeds end-to-end', async () => {
    await seedReflection('reflection-2026-04-28.md', REFLECTION_BODY);
    const result = await runEvolveCommand({
      cwd,
      yes: true,
      autoPr: true,
      ralphFn: makeRalphStub('completed'),
      execFn: makeExecStub({
        // gate + verify path
        'git diff --name-only HEAD': { stdout: 'src/skill.ts\n', stderr: '', exitCode: 0 },
        'git diff --no-color HEAD --': { stdout: '+const x = "clean";\n', stderr: '', exitCode: 0 },
        'npm test': { stdout: 'ok', stderr: '', exitCode: 0 },
        // auto-pr path
        'gh --version': { stdout: 'gh version 2.x', stderr: '', exitCode: 0 },
        'git remote -v': { stdout: 'origin git@github.com:foo/bar.git (push)', stderr: '', exitCode: 0 },
        'git branch --show-current': { stdout: 'feature/x\n', stderr: '', exitCode: 0 },
        'git checkout -b': { stdout: '', stderr: '', exitCode: 0 },
        'git add': { stdout: '', stderr: '', exitCode: 0 },
        'git commit': { stdout: '', stderr: '', exitCode: 0 },
        'git rev-parse HEAD': { stdout: 'abc123\n', stderr: '', exitCode: 0 },
        'git push -u origin': { stdout: '', stderr: '', exitCode: 0 },
        'gh pr create': {
          stdout: 'https://github.com/foo/bar/pull/42\n',
          stderr: '',
          exitCode: 0,
        },
      }),
    });
    expect(result.status).toBe('pr_opened');
    expect(result.prResult?.status).toBe('opened');
    expect(result.prResult?.url).toBe('https://github.com/foo/bar/pull/42');
    expect(result.prResult?.branch).toMatch(/^evolve\//);
  });

  it('auto-pr soft-fails when gh is not installed but evolve is still completed', async () => {
    await seedReflection('reflection-2026-04-28.md', REFLECTION_BODY);
    const result = await runEvolveCommand({
      cwd,
      yes: true,
      autoPr: true,
      ralphFn: makeRalphStub('completed'),
      execFn: makeExecStub({
        'git diff --name-only HEAD': { stdout: 'src/skill.ts\n', stderr: '', exitCode: 0 },
        'git diff --no-color HEAD --': { stdout: '+const x = "clean";\n', stderr: '', exitCode: 0 },
        'npm test': { stdout: 'ok', stderr: '', exitCode: 0 },
        // gh missing
        'gh --version': { stdout: '', stderr: 'command not found', exitCode: 127 },
      }),
    });
    // Evolve itself succeeded; auto-pr soft-failed. Status stays 'completed'.
    expect(result.status).toBe('completed');
    expect(result.prResult?.status).toBe('gh_missing');
  });

  it('does not attempt auto-pr when tests fail', async () => {
    await seedReflection('reflection-2026-04-28.md', REFLECTION_BODY);
    const result = await runEvolveCommand({
      cwd,
      yes: true,
      autoPr: true,
      ralphFn: makeRalphStub('completed'),
      execFn: makeExecStub({
        'git diff --name-only HEAD': { stdout: 'src/skill.ts\n', stderr: '', exitCode: 0 },
        'git diff --no-color HEAD --': { stdout: '+const x = "clean";\n', stderr: '', exitCode: 0 },
        'npm test': { stdout: 'failed', stderr: 'tests', exitCode: 1 },
      }),
    });
    expect(result.status).toBe('tests_failed');
    expect(result.prResult).toBeUndefined();
  });

  // ──────────────────────────────────────────────────────────
  // --worktree mode
  // ──────────────────────────────────────────────────────────

  function makeWorktreeStub(opts: { path?: string; failureReason?: string; cleanedUp?: { value: boolean } } = {}): NonNullable<EvolveCommandOptions['setupWorktreeFn']> {
    const tracker = opts.cleanedUp ?? { value: false };
    return async () => {
      if (opts.failureReason) return { error: opts.failureReason };
      const sandbox: Sandbox = {
        backend: 'gtr',
        path: opts.path ?? '/fake/worktree/path',
        cleanup: async () => {
          tracker.value = true;
        },
      };
      return sandbox;
    };
  }

  it('returns worktree_failed when gtr is not available', async () => {
    await seedReflection('reflection-2026-04-28.md', REFLECTION_BODY);
    const result = await runEvolveCommand({
      cwd,
      worktree: true,
      ralphFn: makeRalphStub('completed'),
      execFn: makeExecStub({}),
      setupWorktreeFn: makeWorktreeStub({ failureReason: 'gtr not installed' }),
    });
    expect(result.status).toBe('worktree_failed');
  });

  it('uses the worktree path as cwd for ralph when --worktree is set', async () => {
    await seedReflection('reflection-2026-04-28.md', REFLECTION_BODY);
    const observedCwds: string[] = [];
    const ralphFn: NonNullable<EvolveCommandOptions['ralphFn']> = async (_prompt, options) => {
      observedCwds.push(options.cwd ?? '');
      return makeRalphStub('completed')(_prompt, options);
    };
    await runEvolveCommand({
      cwd,
      worktree: true,
      ralphFn,
      execFn: makeExecStub({ 'npm test': { stdout: 'ok', stderr: '', exitCode: 0 } }),
      setupWorktreeFn: makeWorktreeStub({ path: '/wt/abc' }),
    });
    expect(observedCwds).toContain('/wt/abc');
    expect(observedCwds).not.toContain(cwd); // user cwd is never passed to ralph
  });

  it('skips the dirty-tree check when --worktree is set', async () => {
    await seedReflection('reflection-2026-04-28.md', REFLECTION_BODY);
    // Even if --yes is NOT set and the user's cwd would be dirty, --worktree skips the check
    const result = await runEvolveCommand({
      cwd,
      worktree: true,
      ralphFn: makeRalphStub('completed'),
      execFn: makeExecStub({
        'git status --porcelain': { stdout: ' M src/foo.ts\n', stderr: '', exitCode: 0 },
        'npm test': { stdout: 'ok', stderr: '', exitCode: 0 },
      }),
      setupWorktreeFn: makeWorktreeStub(),
    });
    // dirty_tree was NOT returned — worktree mode bypasses the check
    expect(result.status).not.toBe('dirty_tree');
  });

  it('cleans up the worktree on success by default', async () => {
    await seedReflection('reflection-2026-04-28.md', REFLECTION_BODY);
    const cleanedUp = { value: false };
    const result = await runEvolveCommand({
      cwd,
      worktree: true,
      ralphFn: makeRalphStub('completed'),
      execFn: makeExecStub({ 'npm test': { stdout: 'ok', stderr: '', exitCode: 0 } }),
      setupWorktreeFn: makeWorktreeStub({ cleanedUp }),
    });
    expect(result.status).toBe('completed');
    expect(cleanedUp.value).toBe(true);
  });

  it('keeps the worktree on success when --keep-worktree is set', async () => {
    await seedReflection('reflection-2026-04-28.md', REFLECTION_BODY);
    const cleanedUp = { value: false };
    await runEvolveCommand({
      cwd,
      worktree: true,
      keepWorktree: true,
      ralphFn: makeRalphStub('completed'),
      execFn: makeExecStub({ 'npm test': { stdout: 'ok', stderr: '', exitCode: 0 } }),
      setupWorktreeFn: makeWorktreeStub({ cleanedUp }),
    });
    expect(cleanedUp.value).toBe(false);
  });

  it('keeps the worktree on failure even without --keep-worktree (so user can debug)', async () => {
    await seedReflection('reflection-2026-04-28.md', REFLECTION_BODY);
    const cleanedUp = { value: false };
    const result = await runEvolveCommand({
      cwd,
      worktree: true,
      ralphFn: makeRalphStub('completed'),
      execFn: makeExecStub({
        // tests fail
        'npm test': { stdout: 'failed', stderr: '5 failures', exitCode: 1 },
      }),
      setupWorktreeFn: makeWorktreeStub({ cleanedUp, path: '/wt/inspect-me' }),
    });
    expect(result.status).toBe('tests_failed');
    expect(cleanedUp.value).toBe(false);
    expect(result.worktreePath).toBe('/wt/inspect-me');
  });

  it('populates worktreePath in the result when --worktree is set', async () => {
    await seedReflection('reflection-2026-04-28.md', REFLECTION_BODY);
    const result = await runEvolveCommand({
      cwd,
      worktree: true,
      keepWorktree: true,
      ralphFn: makeRalphStub('completed'),
      execFn: makeExecStub({ 'npm test': { stdout: 'ok', stderr: '', exitCode: 0 } }),
      setupWorktreeFn: makeWorktreeStub({ path: '/wt/sandbox-42' }),
    });
    expect(result.worktreePath).toBe('/wt/sandbox-42');
  });

  it('does not invoke worktree setup when --worktree is unset', async () => {
    await seedReflection('reflection-2026-04-28.md', REFLECTION_BODY);
    let called = false;
    const setupFn: NonNullable<EvolveCommandOptions['setupWorktreeFn']> = async () => {
      called = true;
      return { error: 'should not be called' };
    };
    const result = await runEvolveCommand({
      cwd,
      yes: true,
      ralphFn: makeRalphStub('completed'),
      execFn: makeExecStub({ 'npm test': { stdout: 'ok', stderr: '', exitCode: 0 } }),
      setupWorktreeFn: setupFn,
    });
    expect(called).toBe(false);
    expect(result.status).toBe('completed');
    expect(result.worktreePath).toBeUndefined();
  });

  it('uses the most recent reflection file when --reflection is unset', async () => {
    await seedReflection('reflection-2026-04-26.md', REFLECTION_BODY);
    const newer = await seedReflection('reflection-2026-04-28.md', REFLECTION_BODY);
    const result = await runEvolveCommand({
      cwd,
      yes: true,
      ralphFn: makeRalphStub('completed'),
      execFn: makeExecStub({ 'npm test': { stdout: 'ok', stderr: '', exitCode: 0 } }),
    });
    expect(result.reflectionPath).toBe(newer);
  });
});
